### ISSUE TITLE
Font Awesome not found when using ember-cli-deploy

### ISSUE THREAD

**Issue by jamesdixon** [martndemus/ember-cli-font-awesome#64]
Hi, 

First off, great addon!

I came across an issue when using [ember-cli-deploy](https://github.com/ember-cli/ember-cli-deploy) to deploy my Ember application, which uses this addon. Unfortunately, [broccoli-asset-rev](https://github.com/rickharrison/broccoli-asset-rev/issues/73) doesn't recognize the cache busting params attached to the end of the [FA font path](https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.css#L9) and subsequently, it doesn't put those URLs through the fingerprinting process, which causes 404s when trying to load FA.

I resolved the issue by overriding the FA css in my own application like so:

```css
// app.css

@font-face {
  font-family: 'FontAwesome';
  src: url('/fonts/fontawesome-webfont.eot');
  src: url('/fonts/fontawesome-webfont.eot') format('embedded-opentype'), url('/fonts/fontawesome-webfont.woff2') format('woff2'), url('/fonts/fontawesome-webfont.woff') format('woff'), url('/fonts/fontawesome-webfont.ttf') format('truetype'), url('/fonts/fontawesome-webfont.svg#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

There probably isn't much you can do about it within the addon, but I just figured I'd make a post here for others who may run into the same issue.

Cheers.
